apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  annotations:
    tekton.dev/docker-0: https://gitlab.com # should be changed to github.com when required.
type: kubernetes.io/basic-auth
stringData:
  username: $(username)
  password: $(password)